import smtplib, ssl

host = "smtp.gmail.com"
port = 465

username = "priyanshisaini2603@gmail.com"
password = "zssptpxqvcxtjbaq"

receiver = "priyanshisaini26@gmail.com"
context = ssl.create_default_context()

message = """\
Subject: Hi!
How are you?
I'm auto generated by priyanshi
Bye!
"""
with smtplib.SMTP_SSL(host, port, context= context) as server:
    server.login(username, password)
    server.sendmail(username, receiver, message)